apiVersion: v1
kind: Service
metadata: 
  name: cricketer-info-service
spec: 
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  type: NodePort
  selector:
    app: cricketer-info